name: Build/release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      # avoid generating multiple releases
      max-parallel: 1
      matrix:
        os: [windows-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Download chars
        shell: bash
        run: |
          ZIP_URL="https://github.com/yafipo/wubi/releases/download/v0.0.0/chars.zip"
          curl -L $ZIP_URL -o chars.zip
          unzip chars.zip -d public

      - name: pnpm installation
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm" # Set this to npm, yarn or pnpm.

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
